name: "Release Windows"

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build
      - name: Build artifacts
        run: flutter build windows --release
      - name: Install openssl
        run: choco install openssl.light
      - name: Get Certificate
        run: |
          New-Item -ItemType directory -Path .\build\github
          Set-Content -Path .\build\github\certificate_encoded.txt -Value '${{ secrets.CERTIFICATE }}'
          certutil -decode .\build\github\certificate_encoded.txt .\build\github\certificate.pfx
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: 'nocab-transfer/NoCabContextMenu'
          latest: true
          filename: 'NoCabContextMenu.dll'
          tarball: false
          zipball: false
          out-file-path: 'build/windows/runner/Release'
      - name: Create MSIX
        run: flutter pub run msix:create -c '.\build\github\certificate.pfx' -p '${{ secrets.PASSWORD }}' -o '.\build\github\' -n 'nocab_desktop-win64-selfsigned_package' --build-windows false --install-certificate false
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: nocab_desktop-win64-portable.zip
          directory: build/windows/runner/Release
          exclusions: NoCabContextMenu.dll
      - name: Generate CRT
        run: openssl pkcs12 -in '.\build\github\certificate.pfx' -clcerts -nokeys -passin pass:${{ secrets.PASSWORD }} | openssl x509 -out .\build\github\public_cert.crt
      - name: Change CRT name
        run: |
          $thumbprint = Get-ChildItem -Path ".\build\github\public_cert.crt" -Force | Get-PfxCertificate | Select-Object -ExpandProperty Thumbprint 
          Rename-Item -Path ".\build\github\public_cert.crt" -NewName "signature-$(echo $thumbprint).crt"
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            ./build/github/signature-*.crt
            ./build/github/nocab_desktop-win64-selfsigned_package.msix
            ./build/windows/runner/Release/nocab_desktop-win64-portable.zip
